export const AppErrorCode = {
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	BAD_REQUEST: 'BAD_REQUEST',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
	UNPROCESSABLE_CONTENT: 'UNPROCESSABLE_CONTENT',
} as const;

export type AppErrorCodeType = (typeof AppErrorCode)[keyof typeof AppErrorCode];
